### PR TITLE
Added *simple* dropdown search

### PR DESCRIPTION
**Pull request by jirijavora**
Added a simple dropdown search (+limited height of people dropdown)

image

### CODE REVIEW

**Comment by jirijavora** [comment]
- [x]  base implementation
- [ ] CSS styling
- [ ] add memoization
- [ ] make it clear which refs are present based on displayed victims - technical improvement

**Comment by sentisso** [comment]
I suggest that we could use full-text search using the [flexsearch library](https://github.com/nextapps-de/flexsearch).

Currently it would be kinda pointless, but it would make more sense if we had more information about the users, such as their full name. This way the library could take an advantage of that and you could search for example only for their surname (and be allowed some typos :)).

I've worked with this library before and it is fairly easy to implement.

**UPDATE:** as I was writing this, I realized that we kinda don't want our full names to be available here lmao nevermind

**Comment by jirijavora** [comment]
Yep, having just the names as they are actually perfectly fits our use case and project theme.

**Comment by jirijavora** [comment]
CSS update can be done at a later date (@jakcharvat has some concept from his attempt at this functionality)

**Pull request merged**
